
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

spring:
  application:
    name: ProjectManagementAPI
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://34.122.8.206/postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
          format_sql: true
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
