apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-management-dep
  labels:
    app: project-management-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-management-api
  template:
    metadata:
      labels:
        app: project-management-api
    spec:
      containers:
        - image: mohammedyb/pmapi
          imagePullPolicy: Always
          name: project-management-api
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pm-service
spec:
  selector:
    app: project-management-api
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pm-ingress
spec:
  tls:
    - hosts:
        - marathon.api.com
      secretName: pm-secret
  rules:
    - host: marathon.api.com
      http:
        paths:
          - path: /master
            pathType: Prefix
            backend:
              service:
                name: pm-service
                port:
                  number: 8080
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: coffee-svc
#                port:
#                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pm-service
spec:
  selector:
    app: project-management-api
  ports:
    - port: 8080
      targetPort: 8080
  externalTrafficPolicy: Local
  type: LoadBalancer
