apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-management-dep
  labels:
    app: project-management-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-management-api
  template:
    metadata:
      labels:
        app: project-management-api
    spec:
      containers:
        - image: mohammedyb/pmapi
          imagePullPolicy: Always
          name: project-management-api
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pm-service
spec:
  selector:
    app: project-management-api
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pmcontroller
annotations:
  nginx.ingress.kubernetes.io/rewrite-target: "/master"
  nginx.ingress.kubernetes.io/ssl-redirect: "false"
  nginx.ingress.kubernetes.io/configuration-snippet: |
spec:
  rules:
 - host: ub.kar.int
     http:
      paths:
      - path: /master(/|$)(.*)
      backend:
        serviceName: jenkins
        servicePort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pm-service
spec:
  selector:
    app: project-management-api
  ports:
    - port: 8080
      targetPort: 8080
  externalTrafficPolicy: Local
  type: LoadBalancer
