
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

spring:
  application:
    name: ProjectManagementAPI
  datasource:
    username: postgres
    password: p@$$w0rd123
    url: jdbc:postgresql://35.232.193.129:5432/postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
          format_sql: true
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 612168336104-vb7fq8q41g1bvevilf0i6hg70n9rd9ov.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

api:
  config:
    api2URL: ${API2URL}