global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yaml

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - api:8080
          - email:8081