
server:
  port: 8081
  servlet:
    context-path:
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: project02sender@gmail.com
    password: sacgpggbsptzcilv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            debug: true