pipeline {
	agent any

	stages {
		stage('Build') {
			steps{
				echo 'Building...'
				sh 'node --version'
				sh 'minikube start'
				//rebuild relevant dockerized apps - Marathon, emailAPI

			}

		}
		stage('Test') {
			steps {
				echo 'Testing...'
				sh 'minikube status'
				//Run through JUnit tests
			}
		}
		stage('Deploy') {
			steps {
				echo 'Deploying...'
				//Docker compose commands
			}

		}
	}
}
