pipeline {
	agent any

	stages {
		stage('Build') {
			steps{
				echo 'Building...'
				sh 'node --version'
				docker build -t main-api ./Project2/ProjectManagementAPI/
				//rebuild relevant dockerized apps - Marathon, emailAPI

			}

		}
		stage('Test') {
			steps {
				echo 'Testing...'
				//Run through JUnit tests
			}
		}
		stage('Deploy') {
			steps {
				echo 'Deploying...'
				//Docker compose commands
			}

		}
	}
}
