pipeline {
	agent any

	stages {
		stage('Build') {
			echo 'Building...'
			//rebuild relevant dockerized apps - Marathon, emailAPI

		}
		stage('Test') {
			echo 'Testing...'
			//Run through JUnit tests
		}
		stage('Deploy') {
			echo 'Deploying...'
			 
		}
	}
}
